apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dineshdocker3246/backend:latest

---
apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  selector:
    app: backend

  ports:
    - name: http
      port: 8080

  type: LoadBalancer

